## SI 670 Applied Machine Learning, Week 4:  Multi-class Classification, SVM, Data Leakage (Due Wednesday 09/28/2022 11:59pm)

For this assignment, you will be practicing various machine learning operations in scikit-learn related to linear regression, polynomial feature expansion and underfitting/overfitting.

* This homework is worth 100 points in total. Correct answers and code receive full credit, but partial credit will be awarded if you have the right idea even if your final answers aren't quite right.

* Submit your completed notebook file to the Canvas site - **IMPORTANT**: please name your submitted file `si670f22-hw4-youruniqname.ipynb`

* Any file submitted after the deadline will be marked as late. Please consult the syllabus regarding late submission policies. You can submit the homework as many time as you want, but only your latest submission will be graded.

* As a reminder, the notebook code you submit must be your own work. Feel free to discuss general approaches to the homework with classmates. If you end up forming more of a team discussion on multiple questions, please include the names of the people you worked with at the top of your notebook file.


### Collaborators, if any:

### Question 1 (20 points)

Please write the answers as well as your derivation process of the following questions. You can use either LaTeX or python code to represent your answer. For example, if you want to present <$x_1^2$>, in the LaTeX format you should write <(dollar sign) x_1^2 (dollar sign)>; in the python code format you should write <\`x_1\*\*2\`>. See [here](https://csrgxtu.github.io/2015/03/20/Writing-Mathematic-Fomulars-in-Markdown/) for how to represent more mathmatical symbols in LaTeX format.

*Note: This question 1 does not require coding.*

<!-- #### (a) (10 points) 

If you have data with features $(x_1, x_2)$, what will be the set of the expanded features after you apply the `PolynomialFeatures` transformation with `degree=3` on it? The order of the features does not matter in your answer.

#### (b) (10 points) 
The main metric we have been using to measure the quality of regression models is $R^2$, which is defined as, for n data points, $R^2 = 1 -  \frac{\sum_{i=1}^n(\hat{y}_i - y_i)^2}{\sum_{i=1}^n(y_i - \bar{y})^2}$, where $y_i, \hat{y}_i$ are the label and prediction of data point i, and $\bar{y} = \frac{1}{n}\sum_{i=1}^n y_i$. We denote $\frac{1}{n}\sum_{i=1}^n(\hat{y}_i - y_i)^2$ as *Unexplained Variation* and $\frac{1}{n}\sum_{i=1}^n(y_i - \bar{y})^2$ as *Total Variation*. 

Given 5 data points with labels (1, 3, 2, -4, 6) and two classifiers A and B, suppose the predictions of A are (1.1, 1.4, 1.3, -2, 2) and the predictions of B are (1.7, 1.3, 0.3, 2, 3). Please calculate and report the *Unexplained Variation*, *Total Variation*, and *$R^2$* for classifiers A and B respectively.  -->

#### (a) (5 points)
Suppose that $w = (3, 4)$ for an SVM decision boundary. What is the margin $M$?

#### (b) (10 points)
Suppose that $(3, 2)$ is a support vector for the SVM above, and its label is $+1$. What is the $b$ for the SVM decision boundary? (Hint: think about the positive plane)

#### (c) (5 points)
You are given 3 data points with two features $x_1$ and $x_2$ and one label $Y$ as follows, (assume that b=0, alpha = 1)

|  X1	| X2 	| Y 	 |
|----	|----	|----	 |
|   1	|  1  | +1   |
| 0.7 |  3 	| -1   |
|   2 | 0.5 | +1   |

Suppose you have a linear classification model where $w = (0.5, 0)$. What is the hinge loss with L2 regularization for this model?

<!-- You are given 3 data points with two features $x_1$ and $x_2$ and one label $Y$ as follows,

|    X1	| X2 	| Y 	|
|----	|----	|----	|
|   1	|   1 	| 1.05 	|
|   0.7 |  3 	| 0.81 	|
|   2   |  0.5 	| 2.045 |

Suppose you have a linear regression model: $\hat{y} = w_1 x_1 + w_2 x_2$, please calculate and report the hinge loss, the L1 regularization, and the L2 regularization terms for each of the following linear models:

(i) $w_1 = 1, w_2 = 0$

(ii) $w_1 = 1, w_2 = 0.02$

If you set the regularization coefficient $\alpha=1$, which of the above two weights is preferred by the Lasso and which is preferred by Ridge regression? Could you use this example to explain why Lasso prefers sparse models? -->


#### Answer 1(a)

Margin M = $ \frac{2}{\sqrt{w^{2}}}$ = $ \frac{2}{\sqrt{3^{2} + 4^{2}}} $ = $\frac{2}{5}$ = 0.4

#### Answer 1(b)

* support vector (x): (3,2)  
* 𝑤=(3,4)  
* label = +1 
* the positive plane = {x : w · x + b = +1} 

$ w · x + b = +1 $   
$ (3,4) · (3,2) + b = +1$    
$ b =  1 - (3*3+4*2) = (-16)$   


#### Answer 1(c)

* b=0, alpha = 1
* x1=(1,1) y1=+1
* x2=(0.7,3) y2=-1
* x3=(2,0.5) y3=+1
* 𝑤=(0.5,0)
* Hinge Loss 
= L(y) 
= $ \left[\frac{1}{n} \sum_{i=1}^n \max \left(0,1-y_i\left(\mathbf{w} \cdot \mathbf{x}_{\mathbf{i}}+b\right)\right)\right]+\alpha\|\mathbf{w}\|^2 $   
= $ \begin{aligned} {\left[\frac{1}{3}[\max (0,1-1 \cdot((0.5,0) \cdot(1,1)))+\max (0,1-(-1) \cdot((0.5,0)(0.7,3)))+\max (0,1-1 \cdot((0.5,0)(2,0.5)))]]\right.}+\sum_{i} W_{i}^{2} \end{aligned}  $   
= $ \frac{1}{3}[0.5+1.35+0]+0.5^{2} $   
= $ \frac{1}{3} \times 1.85+0.25 $   
= $ 0.867 $    


### Question 2 (40 points)

First use `MinMaxScaler` to scale the breast cancer data and then use `GridSearchCV` to search the `kernel`, `C`, and `gamma` parameters for `SVC`. Be careful about the data leakage issues. Please return the best hyper-parameters on cross-validation and the test score associated with the these hyper-parameters.

Please search the `kernel` from ('linear', 'rbf'), `C` from (0.1, 1, 10, 100), `gamma` from (0.1, 1, 10, 100). And please apply `random_state=0` in both `train_test_split`.

*This function should a return a tuple with four numbers, i.e. `(best_kernel, best_C, best_gamma, test_score)`.*

In [2]:
from sklearn.model_selection import GridSearchCV


def answer_two():
    from sklearn.datasets import load_breast_cancer
    from sklearn.model_selection import train_test_split
    from sklearn.preprocessing import MinMaxScaler
    from sklearn.svm import SVC
    from sklearn.model_selection import GridSearchCV
    from sklearn.model_selection import cross_val_score
    import numpy as np
    import operator

    # cancer dataset
    (X_cancer, y_cancer) = load_breast_cancer(return_X_y=True)

    X_train, X_test, y_train, y_test = train_test_split(
        X_cancer, y_cancer, random_state=0)

    scaler = MinMaxScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # hyperparameter and fit
    param_grid = {'C': [0.1, 1, 10, 100],
                  'gamma': [0.1, 1, 10, 100],
                  'kernel': ['linear', 'rbf']}

    grid = GridSearchCV(SVC(), param_grid, refit=True)

    grid.fit(X_train_scaled, y_train)

    # print(grid.best_params_)

    best_kernel = grid.best_params_['kernel']
    best_gamma = grid.best_params_['gamma']
    best_C = grid.best_params_['C']

    # test
    test_score = grid.score(X_test_scaled, y_test)

    return best_kernel, best_C, best_gamma, test_score


answer_two()

('rbf', 1, 1, 0.972027972027972)

### Question 3 (40 points)

Suppose you have a dataset with some missing values and you know the values are not missing at random and the probability of missing is related to the values themselves. For example, people with higher
earnings may be less likely to reveal them. 

#### (a) (5 points) In this case, what would happen when imputing the missing values with the mean strategy?



#### Answer 3(a)

Missing Not at Random, MNAR, means there is a relationship between the propensity of a value to be missing and its values. 

If we impute the missing values with the mean, will decrease our accuracy, and our parameters of interest will be biased, will introduce systematical bias into our model. In the example, the mean will be lower than the actual population mean.




In [2]:
# Please run this cell first before doing question 3(b)

import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression

cancer = load_breast_cancer()
d = {}
for i in range(len(cancer.feature_names)):
    d[cancer.feature_names[i]] = cancer.data[:, i]
d['target'] = cancer.target
df = pd.DataFrame(d)


X = df[['mean concave points', 'worst concave points']]
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(
    np.array(X), np.array(y), random_state=0)
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

lr = LogisticRegression()
lr.fit(X_train, y_train)
print('The performance based on the full data: {:.3f}'.format(
    lr.score(X_test, y_test)))


rng = np.random.RandomState(0)

n_samples = X_train.shape[0]
X_train_missing = X_train.copy()
u = rng.uniform(low=0.3, high=1, size=(n_samples,))
X_train_missing[np.where(u < X_train[:, 0])[0], 0] = np.nan
u = rng.uniform(low=0.3, high=1, size=(n_samples,))
X_train_missing[np.where(u < X_train[:, 1])[0], 1] = np.nan

n_samples = X_test.shape[0]
X_test_missing = X_test.copy()
u = rng.uniform(low=0.3, high=1, size=(n_samples,))
X_test_missing[np.where(u < X_test[:, 0])[0], 0] = np.nan
u = rng.uniform(low=0.3, high=1, size=(n_samples,))
X_test_missing[np.where(u < X_test[:, 1])[0], 1] = np.nan

The performance based on the full data: 0.923


In [3]:
X_train_missing

array([[0.11332008, 0.31484671],
       [0.03768887, 0.06965208],
       [0.48663022, 0.56079917],
       [0.06153082, 0.17860834],
       [0.11466203, 0.30096452],
       [0.04218688, 0.1754392 ],
       [0.10377734, 0.19138822],
       [0.21824056, 0.3191526 ],
       [0.38757455, 0.51842921],
       [0.21744533,        nan],
       [0.15666004, 0.49156045],
       [0.09701789, 0.19249053],
       [0.44875746, 0.55597658],
       [0.14632207, 0.25673441],
       [0.15333002, 0.45780227],
       [0.09120278, 0.12442301],
       [       nan, 0.73062349],
       [0.54821074,        nan],
       [0.04242048, 0.13720289],
       [0.17957256, 0.53565277],
       [0.28508946, 0.59903548],
       [0.14289264, 0.29197382],
       [0.5417495 , 0.87599035],
       [0.29746521, 0.53599724],
       [       nan,        nan],
       [0.18802187, 0.44230107],
       [0.12047714, 0.19338615],
       [0.06371769, 0.08832243],
       [0.09786282, 0.25597658],
       [0.08846918, 0.22487082],
       [0.

#### (b) (10 points) 

Please impute the missing values using `SimpleImputer` with `strategy='mean'`. Then fit a LogisticRegression with default hyper-parameters, and return the imputed data and the test score.


*This function should a return a tuple of two arrays and one number: `(X_train_imputed, X_test_imputed, test_score)`.*


In [33]:
def answer_three_b():
    from sklearn.impute import SimpleImputer
    from sklearn.linear_model import LogisticRegression

    imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
    X_train_imputed = imputer.fit_transform(X_train_missing)
    X_test_imputed = imputer.transform(X_test_missing)

    lr = LogisticRegression().fit(X_train_imputed, y_train)
    test_score = lr.score(X_test_imputed, y_test)

    return (X_train_imputed, X_test_imputed, test_score)


answer_three_b()

(array([[0.11332008, 0.31484671],
        [0.03768887, 0.06965208],
        [0.48663022, 0.56079917],
        [0.06153082, 0.17860834],
        [0.11466203, 0.30096452],
        [0.04218688, 0.1754392 ],
        [0.10377734, 0.19138822],
        [0.21824056, 0.3191526 ],
        [0.38757455, 0.51842921],
        [0.21744533, 0.33000244],
        [0.15666004, 0.49156045],
        [0.09701789, 0.19249053],
        [0.44875746, 0.55597658],
        [0.14632207, 0.25673441],
        [0.15333002, 0.45780227],
        [0.09120278, 0.12442301],
        [0.21115665, 0.73062349],
        [0.54821074, 0.33000244],
        [0.04242048, 0.13720289],
        [0.17957256, 0.53565277],
        [0.28508946, 0.59903548],
        [0.14289264, 0.29197382],
        [0.5417495 , 0.87599035],
        [0.29746521, 0.53599724],
        [0.21115665, 0.33000244],
        [0.18802187, 0.44230107],
        [0.12047714, 0.19338615],
        [0.06371769, 0.08832243],
        [0.09786282, 0.25597658],
        [0.088

#### (c) (10 points) 

Please impute the missing values using `SimpleImputer` with `strategy='mean'` and `add_indicator=True`. Then fit a LogisticRegression with default hyper-parameters, and return the imputed data and the test score.


*This function should a return a tuple of two arrays and one number: `(X_train_imputed, X_test_imputed, test_score)`.*

In [39]:
def answer_three_c():

    from sklearn.impute import SimpleImputer
    from sklearn.linear_model import LogisticRegression

    imputer = SimpleImputer(missing_values=np.nan,
                            strategy='mean', add_indicator=True)
    X_train_imputed = imputer.fit_transform(X_train_missing)
    X_test_imputed = imputer.transform(X_test_missing)

    lr = LogisticRegression().fit(X_train_imputed, y_train)
    test_score = lr.score(X_test_imputed, y_test)

    return (X_train_imputed, X_test_imputed, test_score)

answer_three_c()

(array([[0.11332008, 0.31484671, 0.        , 0.        ],
        [0.03768887, 0.06965208, 0.        , 0.        ],
        [0.48663022, 0.56079917, 0.        , 0.        ],
        ...,
        [0.06988072, 0.17402687, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.20402584, 0.33251808, 0.        , 0.        ]]),
 array([[0.21115665, 0.33000244, 1.        , 1.        ],
        [0.1027833 , 0.20685498, 0.        , 0.        ],
        [0.13180915, 0.28301757, 0.        , 0.        ],
        [0.06829026, 0.25938684, 0.        , 0.        ],
        [0.14527833, 0.17268343, 0.        , 0.        ],
        [0.12892644, 0.29424733, 0.        , 0.        ],
        [0.14801193, 0.33000244, 0.        , 1.        ],
        [0.05705765, 0.19776094, 0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        ],
        [0.10124254, 0.14033758, 0.        , 0.        ],
        [0.31312127, 0.38167413, 0.        , 0.        ],

#### (d) (5 points) 

Why is adding the indicator helpful when the missing values are "missing not at random"?

#### Answer 3(d)

* Including missing data indicators as predictors in the imputation models, this can help us considering MNAR(missing not at random) missingness, reduce bias in estimating outcome models parameters.

